#在这里用centos7作为tomcat的基础镜像
FROM centos:7

#镜像维护者信息
MAINTAINER Lancger@qq.com

#这个环境变量用来表名该镜像模板的最后更新时间
ENV REFRESHED_AT 2020-09-13

#切换镜像目录，进入/usr目录
WORKDIR /usr/local/

#将宿主机的jdk文件添加到镜像中，ADD会帮我们解压到/usr/local/src目录下
ADD apache-tomcat-8.5.57.tar.gz /usr/local/src/

#将宿主机的jdk文件添加到镜像中，ADD会帮我们解压到/usr/local/src目录下
ADD jdk-8u251-linux-x64.tar.gz /usr/local/src/

#覆盖相关文件
COPY server.xml /usr/local/apache-tomcat-8.5.57/conf/

RUN rm -rf /usr/local/apache-tomcat-8.5.57/webapps/* && mkdir -p /usr/local/apache-tomcat-8.5.57/webapps/ROOT && echo "Hello World" >/usr/local/apache-tomcat-8.5.57/webapps/ROOT/index.html

#设置java环境软链
RUN ln -sv /usr/local/src/jdk1.8.0_251 /usr/local/java

#添加java的环境变量（不加这个root登录没有java环境）
ENV JAVA_HOME /usr/local/java
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV CATALINA_HOME /usr/local/apache-tomcat-8.5.57
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/lib:$CATALINA_HOME/bin
ENV TZ="Asia/Shanghai"

ENV JAVA_OPTS="\
-server \
-Xms2048m \
-Xmx2048m \
-Xmn1024m \
-Xss256K \
-Dfile.encoding=UTF-8 \
-Duser.timezone=GMT+08 \
-verbose:gc \
-XX:+UseConcMarkSweepGC \
-XX:MaxTenuringThreshold=10 \
-XX:+ExplicitGCInvokesConcurrent \
-XX:GCTimeRatio=19 \
-XX:+UseParNewGC \
-XX:+UseCMSCompactAtFullCollection \
-XX:CMSFullGCsBeforeCompaction=10 \
-XX:+CMSClassUnloadingEnabled \
-XX:+CMSParallelRemarkEnabled \
-XX:CMSInitiatingOccupancyFraction=75 \
-Xnoclassgc \
-XX:SoftRefLRUPolicyMSPerMB=0"

#JAVA_OPTS="$JAVA_OPTS -server -Xms4096m -Xmx4096m -Xmn2g -Xss256K -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=1024m -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseCMSInitiatingOccupancyOnly -Duser.timezone=GMT+08"

#设置时区，或者 RUN rm -rf /etc/localtime && ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

#公开端口
EXPOSE 8080

#设置启动命令
ENTRYPOINT ["/usr/local/apache-tomcat-8.5.57/bin/catalina.sh", "run"]
